### ISSUE TITLE
Добавьте в readme версию php

### ISSUE THREAD

**Issue by hellaxe** [esasby/hutkigrosh-wordpress4-woocommerce3-module#1]
Не запустилось на 5.4, я не пхпшник, поэтому пришлось помучаться, прежде чем понял, в чем проблема.

**Comment by hellaxe** [comment]
5.5, кстати, тоже не годится, с 5.6 вроде работает

**Comment by nikitamekh** [comment]
Спасибо за замечания. Добавили требования к версии php в readme и composer.json
